### ISSUE TITLE
Different file link leads to cache miss without changing the file content or metadata

### ISSUE THREAD

**Issue by SailReal** [pCloud/pcloud-sdk-java#11]
In the SDK it is mentionded, that I can provide a cache: https://pcloud.github.io/pcloud-sdk-java/com/pcloud/sdk/ApiClient.html#cache--

This works and also the request to create a file link is cached but this download link is different every time I call this method:

https://edef2.pcloud.com/cfZN4ADbkZFDk3PXZExOkZZF4xdG7Z2ZZ6zZZQgUepZ07Z47Zz7Z3ZYZe7Zu7ZX7Zn7ZjZY7Z9Zg7ZdZVRiKK7kcvCbhzj43JVfgiLxKJlGX/V3Y0uyh5ZtLcDfpVdFdnQM6Igw3_VW_mehUbLPy8MiLkruhWcbEA.c9r

https://edef2.pcloud.com/cfZN4ADbkZFDk3PXZExOkZZbmxdG7Z2ZZ6zZZQgUepZ07Z47Zz7Z3ZYZe7Zu7ZX7Zn7ZjZY7Z9Zg7ZdZBOXJfA2krGJ3KDEWVtlzF41huCYV/V3Y0uyh5ZtLcDfpVdFdnQM6Igw3_VW_mehUbLPy8MiLkruhWcbEA.c9r

That means every time it will be a cache miss which results in re downloading from the cloud. Sure I could implement a cache around it but why can I pass a cache to the client when not used while downloading files?

Full log:

```
org.cryptomator.debug D/OkHttp: --> GET https://eapi.pcloud.com/getfilelink?fileid=3058351213 http/1.1 (unknown length)
org.cryptomator.debug D/OkHttp: User-Agent: pCloud SDK Java unspecified
org.cryptomator.debug D/OkHttp: --> END GET
org.cryptomator.debug D/OkHttp: <-- 200 OK https://eapi.pcloud.com/getfilelink?fileid=3058351213 (5777ms)
org.cryptomator.debug D/OkHttp: Server: CloudHTTPd-API v1.1
org.cryptomator.debug D/OkHttp: Date: Wed, 17 Mar 2021 17:32:55 GMT
org.cryptomator.debug D/OkHttp: ETag: "fgFjQhs1lpRMaAopqHCqJBiAzFSV"
org.cryptomator.debug D/OkHttp: Cache-Control: private, max-age=0
org.cryptomator.debug D/OkHttp: Vary: Accept-Encoding
org.cryptomator.debug D/OkHttp: Connection: keep-alive
org.cryptomator.debug D/OkHttp: Keep-Alive: timeout=1800
org.cryptomator.debug D/OkHttp: <-- END HTTP
org.cryptomator.debug D/OkHttp: --> GET https://edef2.pcloud.com/cfZN4ADbkZFDk3PXZExOkZZbmxdG7Z2ZZ6zZZQgUepZ07Z47Zz7Z3ZYZe7Zu7ZX7Zn7ZjZY7Z9Zg7ZdZBOXJfA2krGJ3KDEWVtlzF41huCYV/V3Y0uyh5ZtLcDfpVdFdnQM6Igw3_VW_mehUbLPy8MiLkruhWcbEA.c9r http/1.1 (unknown length)
org.cryptomator.debug D/OkHttp: User-Agent: pCloud SDK Java unspecified
org.cryptomator.debug D/OkHttp: --> END GET


org.cryptomator.debug D/OkHttp: --> GET https://eapi.pcloud.com/getfilelink?fileid=3058351213 http/1.1 (unknown length)
org.cryptomator.debug D/OkHttp: User-Agent: pCloud SDK Java unspecified
org.cryptomator.debug D/OkHttp: --> END GET
org.cryptomator.debug D/OkHttp: <-- 200 OK https://eapi.pcloud.com/getfilelink?fileid=3058351213 (57ms)
org.cryptomator.debug D/OkHttp: Server: CloudHTTPd-API v1.1
org.cryptomator.debug D/OkHttp: Date: Wed, 17 Mar 2021 17:31:54 GMT
org.cryptomator.debug D/OkHttp: ETag: "kuqfgY2CkCVpkReYxM6LRHvGwe8k"
org.cryptomator.debug D/OkHttp: Cache-Control: private, max-age=0
org.cryptomator.debug D/OkHttp: Vary: Accept-Encoding
org.cryptomator.debug D/OkHttp: Connection: keep-alive
org.cryptomator.debug D/OkHttp: Keep-Alive: timeout=1800
org.cryptomator.debug D/OkHttp: <-- END HTTP
org.cryptomator.debug D/OkHttp: --> GET https://edef2.pcloud.com/cfZN4ADbkZFDk3PXZExOkZZbYxdG7Z2ZZ6zZZQgUepZ07Z47Zz7Z3ZYZe7Zu7ZX7Zn7ZjZY7Z9Zg7ZdZMpRwVcanVmfX1WiKevVsmFHuvas7/V3Y0uyh5ZtLcDfpVdFdnQM6Igw3_VW_mehUbLPy8MiLkruhWcbEA.c9r http/1.1 (unknown length)
org.cryptomator.debug D/OkHttp: User-Agent: pCloud SDK Java unspecified
org.cryptomator.debug D/OkHttp: --> END GET
```

**Comment by georgi-neykov-hub** [comment]
@SailReal Thank you for reaching out.

The OkHttp-related options in `ApiClient.Builder` are there to allow reuse of an existing OkHttp client's instances of `Cache`, `ConnectionPool` and `Dispatcher` which are all resource-heavy. OkHttp' cache should do as you've described, cache HTTP responses, and nothing more. Generated file links are short-lived by design to avoid abuse and potential security problems with long-lived links so your problem is the expected behavior. 

One potential workaround is to play with OkHttp's interceptors and intercept the response from `getfilelink`, extract and construct the download link, execute the HTTP request and return the resulting response. Not even sure if it's going to work at all, and I am a bit worried of unintentional side effects from this operation.
One reason is that there would be a problem with file revisions, as in the SDK `getfilelink` will return a link for the latest file revision, so if there is a file modification, the cache will not be invalidated and continue to return the cached response of a file link for a previous revision.

The file revision problem can be fixed by using the `filelink` API call's `hash` parameter which allows getting a file link for a specific file revision. File revision ids are available from the `RemoteFile.hash()` property.


As you see the problem is growing quickly, I can schedule some time to fix the issue with file revisions and generated links as a first step, but I cannot promise anything with the cache misses. 

PCloud's Android client is handling the file link's short lifetime by implementing a system of caches working with keys combining fileid and revision ids. You may try a workaround if the issue is critical by rolling out your own cache, [DiskLruCache](https://github.com/JakeWharton/DiskLruCache) is what's being used in OkHttp's `Cache` implementation.

**Comment by SailReal** [comment]
> ...You may try a workaround if the issue is critical by rolling out your own cache...

It is not really critical but downloading again and again the same file, especially huge ones is really bad for the bandwidth and battery of mobile devices (as well as for your servers :wink:). So yes, we'll implement something like this as we did it with other cloud providers, I was only irritated that you can specify a cache, but this does not solve one of the crucial problems regarding caching: the download of large files. But no problem, then we will implement our own. Thanks for your fast replay.
