### ISSUE TITLE
Listing folders or accessing files fails depending on  pcloud account

### ISSUE THREAD

**Issue by PhilippC** [pCloud/pcloud-sdk-java#42]
I am testing an upgrade of the SDK from 1.2.0  to 1.8.1 (both pcloud-sdk-java-core and pcloud-sdk-android), but I am having trouble to access my files. While log in succeeds, I receive "5000 - internal error" from all calls accessing data in pcloud (e.g. listing files). This has occured since 2 weeks, so it doesn't seem to be a temporary server issue.

Testing the same code with a different account works fine.

What can I do to debug this further?

**Comment by georgi-neykov-hub** [comment]
@PhilippC do you have any more details about users that receive the error, like data region(EU/US), specific country, or specific users? 

One possible reason for the returned error would be pCloud accounts with deep file hierarchies. For such accounts a `listFolder` request with a `recursive=true` for the root or any other folder with 40+ levels of subfolders will be aborted by the API due to stability and availability concerns.

**Comment by PhilippC** [comment]
thanks for that hint! It is true that the account I was testing with is a folder with quite a bit of contents, so probably it did hit that 40+ level limit. 

Note that https://docs.pcloud.com/methods/folder/listfolder.html states
> Recursively listing the root folder is not an expensive operation.

I think this should be removed, it simply seems to be not true.

I changed our implementation to never list recursively.
